package constants

const (
	// CertificateDirectory is the root directory containing all certificates generated by
	// clabernetes manager.
	CertificateDirectory = "/clabernetes/certificates"

	// CertificateAuthoritySubDir is the subdirectory where certificate authority certs are stored.
	CertificateAuthoritySubDir = "ca"

	// ClientCertificateSubDir is the subdirectory where client certs are stored.
	ClientCertificateSubDir = "client"
)
