apiVersion: v1
kind: Service
metadata:
  labels:
    clabernetes/app: clabernetes
    clabernetes/name: topology-basic-srl1
    clabernetes/topologyKind: containerlab
    clabernetes/topologyNode: srl1
    clabernetes/topologyOwner: topology-basic
    clabernetes/topologyServiceType: expose
  name: topology-basic-srl1
  namespace: NAMESPACE
  ownerReferences:
    - apiVersion: clabernetes.containerlab.dev/v1alpha1
      kind: Topology
      name: topology-basic
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: port-161-udp
      port: 161
      protocol: UDP
      targetPort: 60000
    - name: port-21-tcp
      port: 21
      protocol: TCP
      targetPort: 60000
    - name: port-22-tcp
      port: 22
      protocol: TCP
      targetPort: 60001
    - name: port-23-tcp
      port: 23
      protocol: TCP
      targetPort: 60002
    - name: port-80-tcp
      port: 80
      protocol: TCP
      targetPort: 60003
    - name: port-443-tcp
      port: 443
      protocol: TCP
      targetPort: 60004
    - name: port-830-tcp
      port: 830
      protocol: TCP
      targetPort: 60005
    - name: port-5000-tcp
      port: 5000
      protocol: TCP
      targetPort: 60006
    - name: port-5900-tcp
      port: 5900
      protocol: TCP
      targetPort: 60007
    - name: port-6030-tcp
      port: 6030
      protocol: TCP
      targetPort: 60008
    - name: port-9339-tcp
      port: 9339
      protocol: TCP
      targetPort: 60009
    - name: port-9340-tcp
      port: 9340
      protocol: TCP
      targetPort: 60010
    - name: port-9559-tcp
      port: 9559
      protocol: TCP
      targetPort: 60011
    - name: port-57400-tcp
      port: 57400
      protocol: TCP
      targetPort: 60012
  selector:
    clabernetes/app: clabernetes
    clabernetes/name: topology-basic-srl1
    clabernetes/topologyNode: srl1
    clabernetes/topologyOwner: topology-basic
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
