apiVersion: c9s.run/v1alpha1
kind: Topology
metadata:
  annotations: {}
  name: topology-basic
  namespace: NAMESPACE
spec:
  definition:
    containerlab: |-
      name: topology-basic

      topology:
        nodes:
          srl1:
            kind: srl
            image: ghcr.io/nokia/srlinux
            labels:
              c9s.run/exposePorts: "9273/tcp"
status:
  kind: containerlab
  nodeCount: 1
