apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    c9s.run/app: clabernetes
    c9s.run/name: srl1
    c9s.run/topologyNode: srl1
    c9s.run/topologyOwner: clabverter-basic
    c9s.run/topologyServiceType: expose
  name: srl1
  namespace: NAMESPACE
  ownerReferences:
    - apiVersion: c9s.run/v1alpha1
      kind: Node
      name: srl1
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - appProtocol: ftp
      name: port-21-tcp
      port: 21
      protocol: TCP
      targetPort: 21
    - appProtocol: ssh
      name: port-22-tcp
      port: 22
      protocol: TCP
      targetPort: 22
    - appProtocol: telnet
      name: port-23-tcp
      port: 23
      protocol: TCP
      targetPort: 23
    - appProtocol: http
      name: port-80-tcp
      port: 80
      protocol: TCP
      targetPort: 80
    - appProtocol: https
      name: port-443-tcp
      port: 443
      protocol: TCP
      targetPort: 443
    - appProtocol: netconf-ssh
      name: port-830-tcp
      port: 830
      protocol: TCP
      targetPort: 830
    - appProtocol: telnet
      name: port-5000-tcp
      port: 5000
      protocol: TCP
      targetPort: 5000
    - appProtocol: rfb
      name: port-5900-tcp
      port: 5900
      protocol: TCP
      targetPort: 5900
    - appProtocol: c9s.run/gnmi
      name: port-6030-tcp
      port: 6030
      protocol: TCP
      targetPort: 6030
    - appProtocol: c9s.run/gnmi
      name: port-9339-tcp
      port: 9339
      protocol: TCP
      targetPort: 9339
    - appProtocol: c9s.run/gribi
      name: port-9340-tcp
      port: 9340
      protocol: TCP
      targetPort: 9340
    - appProtocol: c9s.run/p4runtime
      name: port-9559-tcp
      port: 9559
      protocol: TCP
      targetPort: 9559
    - appProtocol: c9s.run/gnmi
      name: port-57400-tcp
      port: 57400
      protocol: TCP
      targetPort: 57400
    - appProtocol: snmp
      name: port-161-udp
      port: 161
      protocol: UDP
      targetPort: 161
  selector:
    c9s.run/app: clabernetes
    c9s.run/name: srl1
    c9s.run/topologyNode: srl1
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
