apiVersion: clabernetes.containerlab.dev/v1alpha1
kind: Topology
metadata:
  annotations: {}
  name: clabverter-basic
  namespace: NAMESPACE
spec:
  connectivity: vxlan
  definition:
    containerlab: |-
      ---
      name: clabverter-basic

      topology:
        nodes:
          srl1:
            kind: srl
            image: ghcr.io/nokia/srlinux
          srl2:
            kind: srl
            image: ghcr.io/nokia/srlinux

        links:
          - endpoints: ["srl1:e1-1", "srl2:e1-1"]
  deployment:
    persistence:
      enabled: false
    scheduling: {}
  expose:
    disableAutoExpose: false
    disableExpose: false
  imagePull: {}
status:
  configs:
    srl1: |
      name: clabernetes-srl1
      prefix: ""
      topology:
          defaults:
              ports:
                  - 60000:21/tcp
                  - 60001:22/tcp
                  - 60002:23/tcp
                  - 60003:80/tcp
                  - 60000:161/udp
                  - 60004:443/tcp
                  - 60005:830/tcp
                  - 60006:5000/tcp
                  - 60007:5900/tcp
                  - 60008:6030/tcp
                  - 60009:9339/tcp
                  - 60010:9340/tcp
                  - 60011:9559/tcp
                  - 60012:57400/tcp
          nodes:
              srl1:
                  kind: srl
                  image: ghcr.io/nokia/srlinux
                  ports: []
          links:
              - endpoints:
                  - srl1:e1-1
                  - host:srl1-e1-1
      debug: false
    srl2: |
      name: clabernetes-srl2
      prefix: ""
      topology:
          defaults:
              ports:
                  - 60000:21/tcp
                  - 60001:22/tcp
                  - 60002:23/tcp
                  - 60003:80/tcp
                  - 60000:161/udp
                  - 60004:443/tcp
                  - 60005:830/tcp
                  - 60006:5000/tcp
                  - 60007:5900/tcp
                  - 60008:6030/tcp
                  - 60009:9339/tcp
                  - 60010:9340/tcp
                  - 60011:9559/tcp
                  - 60012:57400/tcp
          nodes:
              srl2:
                  kind: srl
                  image: ghcr.io/nokia/srlinux
                  ports: []
          links:
              - endpoints:
                  - srl2:e1-1
                  - host:srl2-e1-1
      debug: false
  exposedPorts:
    srl1:
      tcpPorts:
        - 21
        - 22
        - 23
        - 80
        - 443
        - 830
        - 5000
        - 5900
        - 6030
        - 9339
        - 9340
        - 9559
        - 57400
      udpPorts:
        - 161
    srl2:
      tcpPorts:
        - 21
        - 22
        - 23
        - 80
        - 443
        - 830
        - 5000
        - 5900
        - 6030
        - 9339
        - 9340
        - 9559
        - 57400
      udpPorts:
        - 161
  kind: containerlab
  reconcileHashes:
    config: 25ea403243c3741d3013049756aa02db0ad8dc3d0d9bf803dc1576f9dda33649
    filesFromURL: {}
    imagePullSecrets: 37517e5f3dc66819f61f5a7bb8ace1921282415f10551d2defa5c3eb0985b570
