apiVersion: c9s.run/v1alpha1
kind: Topology
metadata:
  annotations: {}
  name: clabverter-basic
  namespace: NAMESPACE
spec:
  definition:
    containerlab: |-
      ---
      name: clabverter-basic

      topology:
        nodes:
          srl1:
            kind: srl
            image: ghcr.io/nokia/srlinux
          srl2:
            kind: srl
            image: ghcr.io/nokia/srlinux

        links:
          - endpoints: ["srl1:e1-1", "srl2:e1-1"]
          - endpoints: ["srl1:e1-3", "host:eth13"]
status:
  kind: containerlab
  linkCount: 2
  nodeCount: 2
