---
apiVersion: clabernetes.containerlab.dev/v1alpha1
kind: Topology
metadata:
  name: clab-srl02
  namespace: srl02
spec:
  definition:
    containerlab: |-
      name: srl02
      topology:
        nodes:
          srl1:
            kind: nokia_srlinux
            image: ghcr.io/nokia/srlinux:23.7.1
            startup-config: |
              set / interface ethernet-1/1
              set / interface ethernet-1/1 subinterface 0
              set / interface ethernet-1/1 subinterface 0 ipv4
              set / interface ethernet-1/1 subinterface 0 ipv4 admin-state enable
              set / interface ethernet-1/1 subinterface 0 ipv4 address 192.168.0.0/31
              set / interface ethernet-1/1 subinterface 0 ipv6
              set / interface ethernet-1/1 subinterface 0 ipv6 admin-state enable
              set / interface ethernet-1/1 subinterface 0 ipv6 address 2002::192.168.0.0/127
              set / network-instance default
              set / network-instance default interface ethernet-1/1.0
  
          srl2:
            kind: nokia_srlinux
            image: ghcr.io/nokia/srlinux:23.7.1
            startup-config: |
              set / interface ethernet-1/1 admin-state enable
              set / interface ethernet-1/1 subinterface 0
              set / interface ethernet-1/1 subinterface 0 ipv4
              set / interface ethernet-1/1 subinterface 0 ipv4 admin-state enable
              set / interface ethernet-1/1 subinterface 0 ipv4 address 192.168.0.1/31
              set / interface ethernet-1/1 subinterface 0 ipv6
              set / interface ethernet-1/1 subinterface 0 ipv6 admin-state enable
              set / interface ethernet-1/1 subinterface 0 ipv6 address 2002::192.168.0.1/127
              set / network-instance default
              set / network-instance default interface ethernet-1/1.0
  
        links:
          - endpoints: ["srl1:e1-1", "srl2:e1-1"]
