# Nokia SR-SIM Example
# This example demonstrates deploying Nokia SR OS Simulator with clabernetes.
#
# SR-SIM System Types:
# - Integrated systems (sr-1, sr-1s): Single container per router
# - Distributed chassis (sr-7, sr-14s): Multiple containers per chassis
#   (CPM-A, CPM-B for control plane, IOM-1, IOM-2, etc. for line cards)
#   These are grouped into a single Kubernetes pod using network-mode.
#
# IMPORTANT:
# - A valid SR-SIM license is required
# - The SR-SIM image must be loaded into your container runtime
#
# See docs/guides/nokia-srsim.md for full documentation
apiVersion: clabernetes.containerlab.dev/v1alpha1
kind: Topology
metadata:
  name: nokia-srsim
spec:
  # Resource configuration for SR-SIM routers (resource intensive)
  # These are keyed by containerlab node name (the router name in topology.nodes)
  deployment:
    resources:
      router1:
        requests:
          memory: "4Gi"
          cpu: "2"
        limits:
          memory: "8Gi"
          cpu: "4"
      router2:
        requests:
          memory: "4Gi"
          cpu: "2"
        limits:
          memory: "8Gi"
          cpu: "4"
  definition:
    containerlab: |
      name: nokia-srsim
      topology:
        kinds:
          nokia_srsim:
            # SR-SIM image - must be loaded from Nokia Support Portal
            image: nokia_srsim:25.7.R1
            # License is mandatory for SR-SIM
            license: /opt/nokia/sros/license.txt
        nodes:
          router1:
            kind: nokia_srsim
            # Integrated system type (sr-1 is default)
            type: sr-1
            # Optional: Configure MDAs via environment variables
            env:
              NOKIA_SROS_MDA_1: me6-100gb-qsfp28
          router2:
            kind: nokia_srsim
            type: sr-1s
        links:
          # SR-SIM interface format: L/M/cC/P (card/mda/connector/port)
          - endpoints: ["router1:1/1/c1/1", "router2:1/1/c1/1"]
