# Topology using slurpeeth connectivity mode (experimental)
# Uses TCP tunnels instead of VXLAN for inter-node connectivity
# Avoids VXLAN MTU and fragmentation issues
apiVersion: clabernetes.containerlab.dev/v1alpha1
kind: Topology
metadata:
  name: slurpeeth-topo
spec:
  # Use slurpeeth instead of default vxlan
  connectivity: slurpeeth
  definition:
    containerlab: |
      name: slurpeeth
      topology:
        nodes:
          srl1:
            kind: nokia_srlinux
            image: ghcr.io/nokia/srlinux:latest
          srl2:
            kind: nokia_srlinux
            image: ghcr.io/nokia/srlinux:latest
          srl3:
            kind: nokia_srlinux
            image: ghcr.io/nokia/srlinux:latest
        links:
          - endpoints: ["srl1:e1-1", "srl2:e1-1"]
          - endpoints: ["srl2:e1-2", "srl3:e1-1"]
          - endpoints: ["srl3:e1-2", "srl1:e1-2"]
