{{- if .Values.globalConfig.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    revision: "{{ .Release.Revision }}"
    c9s.run/app: {{ .Values.appName }}
    c9s.run/name: "{{ .Values.appName }}-config"
    c9s.run/component: config
    {{- if .Values.globalLabels }}
{{ .Values.globalLabels | toYaml | indent 4 }}
    {{- end }}
  {{- if .Values.globalAnnotations }}
  annotations:
{{ .Values.globalAnnotations | toYaml | indent 4 }}
  {{- end }}
data:
  mergeMode: {{ .Values.globalConfig.mergeMode }}
  globalAnnotations: |-
    ---
{{ .Values.globalAnnotations | toYaml | indent 4 }}
  globalLabels: |-
    ---
{{ .Values.globalLabels | toYaml | indent 4 }}
  resourcesDefault: |-
    ---
{{ .Values.globalConfig.deployment.resourcesDefault | toYaml | indent 4 }}
  nodeSelectorsByImage: |-
{{ .Values.globalConfig.deployment.nodeSelectorsByImage | toYaml | indent 4 }}
    ---
  containerStopSignals: "{{ .Values.globalConfig.deployment.containerStopSignals }}"
  imagePullPolicy: {{ .Values.globalConfig.imagePull.policy }}
  imagePullSecrets: |-
{{ .Values.globalConfig.imagePull.pullSecrets | toYaml | indent 4 }}
  {{- if .Values.globalConfig.imagePull.registryMetadataTrust }}
  registryMetadataTrust: |-
{{ .Values.globalConfig.imagePull.registryMetadataTrust | toYaml | indent 4 }}
  {{- end }}
  {{- if .Values.globalConfig.imagePull.registryMetadataMirrors }}
  registryMetadataMirrors: |-
{{ .Values.globalConfig.imagePull.registryMetadataMirrors | toYaml | indent 4 }}
  {{- end }}
{{- end }}
