//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
  Copyright The Kubernetes Authors.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	topology "gitlab.com/carlmontanari/clabernetes/apis/topology"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Containerlab) DeepCopyInto(out *Containerlab) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Containerlab.
func (in *Containerlab) DeepCopy() *Containerlab {
	if in == nil {
		return nil
	}
	out := new(Containerlab)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Containerlab) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerlabList) DeepCopyInto(out *ContainerlabList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Containerlab, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerlabList.
func (in *ContainerlabList) DeepCopy() *ContainerlabList {
	if in == nil {
		return nil
	}
	out := new(ContainerlabList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContainerlabList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerlabSpec) DeepCopyInto(out *ContainerlabSpec) {
	*out = *in
	if in.InsecureRegistries != nil {
		in, out := &in.InsecureRegistries, &out.InsecureRegistries
		*out = make(topology.InsecureRegistries, len(*in))
		copy(*out, *in)
	}
	if in.FilesFromConfigMap != nil {
		in, out := &in.FilesFromConfigMap, &out.FilesFromConfigMap
		*out = make([]FileFromConfigMap, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerlabSpec.
func (in *ContainerlabSpec) DeepCopy() *ContainerlabSpec {
	if in == nil {
		return nil
	}
	out := new(ContainerlabSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerlabStatus) DeepCopyInto(out *ContainerlabStatus) {
	*out = *in
	if in.Tunnels != nil {
		in, out := &in.Tunnels, &out.Tunnels
		*out = make(map[string][]*topology.Tunnel, len(*in))
		for key, val := range *in {
			var outVal []*topology.Tunnel
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make([]*topology.Tunnel, len(*in))
				for i := range *in {
					if (*in)[i] != nil {
						in, out := &(*in)[i], &(*out)[i]
						*out = new(topology.Tunnel)
						**out = **in
					}
				}
			}
			(*out)[key] = outVal
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerlabStatus.
func (in *ContainerlabStatus) DeepCopy() *ContainerlabStatus {
	if in == nil {
		return nil
	}
	out := new(ContainerlabStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileFromConfigMap) DeepCopyInto(out *FileFromConfigMap) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileFromConfigMap.
func (in *FileFromConfigMap) DeepCopy() *FileFromConfigMap {
	if in == nil {
		return nil
	}
	out := new(FileFromConfigMap)
	in.DeepCopyInto(out)
	return out
}
