---
name: build

on:
  workflow_call: {}
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
            platform: linux/amd64
            runner: ubuntu-24.04
          - arch: arm64
            platform: linux/arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: load env vars for workflow run
        run: |
          source .github/vars.env
          echo "GO_VERSION=$GO_VERSION" >> "$GITHUB_ENV"
          echo "DEVSPACE_VERSION=$DEVSPACE_VERSION" >> "$GITHUB_ENV"
          echo "GCI_VERSION=$GCI_VERSION" >> "$GITHUB_ENV"
          echo "GOFUMPT_VERSION=$GOFUMPT_VERSION" >> "$GITHUB_ENV"
          echo "GOLANGCI_LINT_VERSION=$GOLANGCI_LINT_VERSION" >> "$GITHUB_ENV"
          echo "GOLINES_VERSION=$GOLINES_VERSION" >> "$GITHUB_ENV"
          echo "GOTESTSUM_VERSION=$GOTESTSUM_VERSION" >> "$GITHUB_ENV"
          echo "HELM_VERSION=$HELM_VERSION" >> "$GITHUB_ENV"
          echo "YQ_VERSION=$YQ_VERSION" >> "$GITHUB_ENV"

      - name: store short hash
        run: |
          echo "COMMIT_HASH=$(git describe --always --abbrev=8)" >> "$GITHUB_ENV"

      - name: login to ghcr
        if: github.ref_name == 'main'
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: set up buildx
        uses: docker/setup-buildx-action@v4

      - name: build images
        run: |
          PUSH="${{ github.ref_name == 'main' && 'true' || 'false' }}" \
            PLATFORMS="${{ matrix.platform }}" \
            BUILD_VERSION="0.0.0-${{ env.COMMIT_HASH }}" \
            IMAGE_TAGS="dev-latest,${{ env.COMMIT_HASH }}" \
            IMAGE_TAG_SUFFIX="-${{ matrix.arch }}" \
            bash hack/build-images.sh

  publish:
    if: github.ref_name == 'main'
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: load env vars for workflow run
        run: |
          source .github/vars.env
          echo "HELM_VERSION=$HELM_VERSION" >> "$GITHUB_ENV"

      - name: store short hash
        run: |
          echo "COMMIT_HASH=$(git describe --always --abbrev=8)" >> "$GITHUB_ENV"

      - name: install helm
        run: |
          curl -L -o helm.tar.gz \
            "https://get.helm.sh/helm-${{ env.HELM_VERSION }}-linux-amd64.tar.gz"
          tar -zxvf helm.tar.gz
          mv linux-amd64/helm /usr/local/bin/helm
        working-directory: /tmp

      - name: login to ghcr
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: set up buildx
        uses: docker/setup-buildx-action@v4

      - name: publish image manifests and helm chart
        run: |
          IMAGE_TAGS="dev-latest,${{ env.COMMIT_HASH }}" \
            bash hack/create-image-manifests.sh

          helm registry login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
          
          helm package charts/clicker --version 0.0.0
          helm push clicker-0.0.0.tgz oci://ghcr.io/srl-labs/clabernetes
          
          # patch clicker dep version so its always same as c9s
          sed -i \
            's|    version: (.*)|    version: 0.0.0|g' \
            charts/clabernetes/Chart.yaml
          helm package charts/clabernetes --version 0.0.0
          helm push clabernetes-0.0.0.tgz oci://ghcr.io/srl-labs/clabernetes
