---
name: lint

on:
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: load env vars for workflow run
        run: cat .github/vars.env >> "$GITHUB_ENV"

      - name: set up go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: ensure go mod is tidy
        run: |
          git diff --exit-code --name-only go.mod go.sum 2>&1

      - name: install lint tools
        run: make install-lint-tools

      - name: run the linters
        run: make lint
