---
name: release

on:
  release:
    types:
      - created

permissions:
  contents: write
  packages: write

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml

  test:
    uses: ./.github/workflows/test.yaml

  prep:
    needs:
      - lint
      - test
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.v.outputs.version }}
    steps:
      - name: set release version
        id: v
        run: |
          RELEASE_TAG=${{ github.ref_name }}
          echo "version=${RELEASE_TAG#v}" >> "$GITHUB_OUTPUT"

  images:
    needs: prep
    uses: ./.github/workflows/images.yaml
    with:
      push: true
      build-version: ${{ needs.prep.outputs.version }}
    secrets: inherit

  release:
    needs:
      - prep
      - images
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: load env vars for workflow run
        run: cat .github/vars.env >> "$GITHUB_ENV"

      - name: install helm
        run: make install-helm

      - name: login to ghcr
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # note: we run goreleaser before any helm packaging since helm updates the chart.yaml files
      # w/ the release tag/version which upsets goreleaser (and we dont want to .gitignore the chart
      # manifest obviously)
      - name: run goreleaser to build clabverter/checksums
        uses: goreleaser/goreleaser-action@v7
        with:
          version: ${{ env.GORELEASER_VERSION }}
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: ${{ needs.prep.outputs.version }}

      # simply use gh cli to upload since we dont actually want an action that makes the release
      # for us, just wanna upload assets
      - name: upload clabverter binaries (and checksums) to the release
        run: |
          cd .dist
          gh release upload ${{ github.ref_name }} checksums.txt
          for filename in *.tar.gz; do
            [ -e "$filename" ] || continue
            gh release upload ${{ github.ref_name }} "$filename"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash

      - name: package and push charts
        run: |
          helm registry login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io

          make set-chart-versions ${{ needs.prep.outputs.version }}

          helm package charts/clicker --version ${{ needs.prep.outputs.version }}
          helm push clicker-${{ needs.prep.outputs.version }}.tgz oci://ghcr.io/srl-labs/clabernetes

          helm package charts/clabernetes --version ${{ needs.prep.outputs.version }}
          helm push clabernetes-${{ needs.prep.outputs.version }}.tgz oci://ghcr.io/srl-labs/clabernetes
